<a href="https://colab.research.google.com/github/dachasa/Prediccion-Temporada-70-71/blob/main/Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Libro1.csv',delimiter=';')

In [3]:
df

Unnamed: 0  Jornada 1  ...  Jornada 29  Jornada 30
0   Atletico de Bilbao          0  ...           1           1
1   Atletico de Bilbao          0  ...           1           0
2   Atletico de Madrid          0  ...           0           0
3   Atletico de Madrid          1  ...           1           0
4            Barcelona          0  ...           1           0
5            Barcelona          1  ...           0           1
6            CD Malaga          0  ...           0           1
7            CD Malaga          1  ...           0           1
8        Celta de Vigo          1  ...           1           0
9        Celta de Vigo          0  ...           1           0
10               Elche          0  ...           1           1
11               Elche          0  ...           1           0
12             Espanol          2  ...           1           1
13             Espanol          0  ...           1           0
14             Granada          0  ...           1           2
15             Granada          1  ...           0           1
16          Las Palmas          0  ...           1           0
17          Las Palmas          0  ...           1           0
18         Real Madrid          1  ...           1           0
19         Real Madrid          0  ...           0           1
20       Real Sociedad          0  ...           1           0
21       Real Sociedad          1  ...           0           1
22            Sabadell          0  ...           1           2
23            Sabadell          0  ...           1           0
24             Sevilla          2  ...           1           1
25             Sevilla          1  ...           0           1
26   Sporting de Gijon          1  ...           1           0
27   Sporting de Gijon          1  ...           0           1
28            Valencia          1  ...           1           1
29            Valencia          1  ...           0           1
30            Zaragoza          0  ...           1           0
31            Zaragoza          0  ...           1           0

[32 rows x 31 columns]

In [4]:
import numpy as np

In [5]:
equipos = np.unique(df.iloc[:,0])

In [6]:
resultados = pd.read_csv('Resultados.csv',delimiter=';')

In [7]:
resultados

Jornada             Equipo1            Equipo2  Resultado
0          6  Atletico de Bilbao           Sabadell          1
1          6  Atletico de Madrid              Elche          1
2          6           Barcelona            Espanol          1
3          6   Sporting de Gijon           Valencia          2
4          6             Granada         Las Palmas          1
..       ...                 ...                ...        ...
195       30               Elche            Sevilla          1
196       30             Espanol           Valencia          1
197       30          Las Palmas        Real Madrid          0
198       30            Sabadell            Granada          2
199       30            Zaragoza  Sporting de Gijon          0

[200 rows x 4 columns]

In [8]:
len(resultados)

200

In [9]:
def extraerFila(equipo1,equipo2,jornada):
  resEq1 = list(df[df['Unnamed: 0']==equipo1].iloc[:,jornada-5:jornada].values[0])+list(df[df['Unnamed: 0']==equipo1].iloc[:,jornada-5:jornada].values[1])
  resEq2 = list(df[df['Unnamed: 0']==equipo2].iloc[:,jornada-5:jornada].values[0])+list(df[df['Unnamed: 0']==equipo2].iloc[:,jornada-5:jornada].values[1])
  return resEq1+resEq2

In [10]:
extraerFila('Zaragoza','Las Palmas',7)

[1, 2, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1]

In [11]:
extraerFila('Atletico de Bilbao','Sabadell',6)

[0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 2, 0, 1, 0, 1, 0]

In [12]:
for (jor,eq1,eq2,res) in resultados.values:
  print([eq1]+[eq2]+extraerFila(eq1,eq2,jor)+[res])

['Atletico de Bilbao', 'Sabadell', 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 2, 0, 1, 0, 1, 0, 1]
['Atletico de Madrid', 'Elche', 0, 1, 2, 1, 2, 1, 0, 1, 0, 1, 0, 1, 1, 1, 2, 0, 1, 0, 1, 0, 1]
['Barcelona', 'Espanol', 0, 1, 0, 1, 2, 1, 0, 1, 0, 1, 2, 1, 0, 2, 0, 0, 1, 0, 1, 0, 1]
['Sporting de Gijon', 'Valencia', 1, 1, 1, 2, 0, 1, 0, 1, 0, 1, 1, 1, 2, 0, 0, 1, 0, 0, 1, 0, 2]
['Granada', 'Las Palmas', 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1]
['CD Malaga', 'Real Madrid', 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 2]
['Real Sociedad', 'Sevilla', 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 2, 1, 2, 0, 1, 1, 0, 1, 1, 0, 1]
['Zaragoza', 'Celta de Vigo', 0, 1, 2, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0]
['Elche', 'Atletico de Bilbao', 1, 1, 1, 2, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0]
['Espanol', 'Atletico de Madrid', 1, 0, 2, 0, 1, 1, 0, 1, 0, 1, 1, 2, 1, 2, 1, 0, 1, 0, 1, 0, 0]
['Granada', 'Real Sociedad', 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0,

In [13]:
lista=[['Equipo1','Equipo2','JEquipo1_(N-5)','JEquipo1_(N-4)','JEquipo1_(N-3)','JEquipo1_(N-2)','JEquipo1_(N-1)','JEquipo1_(N-5)LV','JEquipo1_(N-4)LV','JEquipo1_(N-3)LV','JEquipo1_(N-2)LV','JEquipo1_(N-1)LV','JEquipo2_(N-5)','JEquipo2_(N-4)','JEquipo2_(N-3)','JEquipo2_(N-2)','JEquipo2_(N-1)','JEquipo2_(N-5)LV','JEquipo2_(N-4)LV','JEquipo2_(N-3)LV','JEquipo2_(N-2)LV','JEquipo2_(N-1)LV','Resultado']]
for (jor,eq1,eq2,res) in resultados.values:
  lista.append([eq1]+[eq2]+extraerFila(eq1,eq2,jor)+[res])
print(lista)

[['Equipo1', 'Equipo2', 'JEquipo1_(N-5)', 'JEquipo1_(N-4)', 'JEquipo1_(N-3)', 'JEquipo1_(N-2)', 'JEquipo1_(N-1)', 'JEquipo1_(N-5)LV', 'JEquipo1_(N-4)LV', 'JEquipo1_(N-3)LV', 'JEquipo1_(N-2)LV', 'JEquipo1_(N-1)LV', 'JEquipo2_(N-5)', 'JEquipo2_(N-4)', 'JEquipo2_(N-3)', 'JEquipo2_(N-2)', 'JEquipo2_(N-1)', 'JEquipo2_(N-5)LV', 'JEquipo2_(N-4)LV', 'JEquipo2_(N-3)LV', 'JEquipo2_(N-2)LV', 'JEquipo2_(N-1)LV', 'Resultado'], ['Atletico de Bilbao', 'Sabadell', 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 2, 0, 1, 0, 1, 0, 1], ['Atletico de Madrid', 'Elche', 0, 1, 2, 1, 2, 1, 0, 1, 0, 1, 0, 1, 1, 1, 2, 0, 1, 0, 1, 0, 1], ['Barcelona', 'Espanol', 0, 1, 0, 1, 2, 1, 0, 1, 0, 1, 2, 1, 0, 2, 0, 0, 1, 0, 1, 0, 1], ['Sporting de Gijon', 'Valencia', 1, 1, 1, 2, 0, 1, 0, 1, 0, 1, 1, 1, 2, 0, 0, 1, 0, 0, 1, 0, 2], ['Granada', 'Las Palmas', 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1], ['CD Malaga', 'Real Madrid', 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 2], ['Real Sociedad',

In [14]:
import csv

In [15]:
with open('1970-71.csv', 'w') as csvfile:
    writer = csv.writer(csvfile, delimiter=',', quotechar='|',
                        quoting=csv.QUOTE_MINIMAL)
    writer.writerows(lista)

# Modelo de predicción para la temporada 1970-71

In [16]:
Temporada70=pd.read_csv('1970-71.csv')

In [17]:
Temporada70

Equipo1            Equipo2  ...  JEquipo2_(N-1)LV  Resultado
0    Atletico de Bilbao           Sabadell  ...                 0          1
1    Atletico de Madrid              Elche  ...                 0          1
2             Barcelona            Espanol  ...                 0          1
3     Sporting de Gijon           Valencia  ...                 0          2
4               Granada         Las Palmas  ...                 1          1
..                  ...                ...  ...               ...        ...
195               Elche            Sevilla  ...                 0          1
196             Espanol           Valencia  ...                 0          1
197          Las Palmas        Real Madrid  ...                 0          0
198            Sabadell            Granada  ...                 0          2
199            Zaragoza  Sporting de Gijon  ...                 0          0

[200 rows x 23 columns]

# Aplicando One-Hot Encoding

Para a las variables categóricas les deberemos aplicar la técnica one-hot encoding: Esta técnica crea 16 nuevas columnas(número de equipos en la temporada 70) en los datos de manera que en dichas columnas habrá un 1 si la columna corresponde con el equipo y 0 en caso contrario. 

Generaremos columnas de tipo dummy en las columnas de Equipo1 y Equipo2

In [18]:
Equipo1_dummy=pd.get_dummies(Temporada70['Equipo1'],prefix='EquipoLocal')
Equipo2_dummy=pd.get_dummies(Temporada70['Equipo2'],prefix='EquipoVisitante')

Unimos las columnas de tipo dummy a la información general del archivo

In [19]:
Temporada70=pd.concat([Temporada70,Equipo1_dummy],axis=1)
Temporada70=pd.concat([Temporada70,Equipo2_dummy],axis=1)

In [20]:
Temporada70

Equipo1  ... EquipoVisitante_Zaragoza
0    Atletico de Bilbao  ...                        0
1    Atletico de Madrid  ...                        0
2             Barcelona  ...                        0
3     Sporting de Gijon  ...                        0
4               Granada  ...                        0
..                  ...  ...                      ...
195               Elche  ...                        0
196             Espanol  ...                        0
197          Las Palmas  ...                        0
198            Sabadell  ...                        0
199            Zaragoza  ...                        0

[200 rows x 55 columns]

In [21]:
Temporada70=Temporada70.drop(['Equipo1','Equipo2'], axis= 1)

In [22]:
Temporada70

JEquipo1_(N-5)  ...  EquipoVisitante_Zaragoza
0                 0  ...                         0
1                 0  ...                         0
2                 0  ...                         0
3                 1  ...                         0
4                 0  ...                         0
..              ...  ...                       ...
195               0  ...                         0
196               2  ...                         0
197               1  ...                         0
198               0  ...                         0
199               1  ...                         0

[200 rows x 53 columns]

Ordenamos las nuevas columnas, para que las primeras salgan si un equipo juega de local o visitante, después los datos de las 5 jornadas anteriores, y por último el resultado del partido.

In [23]:
cols=list(Temporada70.columns)
cols

['JEquipo1_(N-5)',
 'JEquipo1_(N-4)',
 'JEquipo1_(N-3)',
 'JEquipo1_(N-2)',
 'JEquipo1_(N-1)',
 'JEquipo1_(N-5)LV',
 'JEquipo1_(N-4)LV',
 'JEquipo1_(N-3)LV',
 'JEquipo1_(N-2)LV',
 'JEquipo1_(N-1)LV',
 'JEquipo2_(N-5)',
 'JEquipo2_(N-4)',
 'JEquipo2_(N-3)',
 'JEquipo2_(N-2)',
 'JEquipo2_(N-1)',
 'JEquipo2_(N-5)LV',
 'JEquipo2_(N-4)LV',
 'JEquipo2_(N-3)LV',
 'JEquipo2_(N-2)LV',
 'JEquipo2_(N-1)LV',
 'Resultado',
 'EquipoLocal_Atletico de Bilbao',
 'EquipoLocal_Atletico de Madrid',
 'EquipoLocal_Barcelona',
 'EquipoLocal_CD Malaga',
 'EquipoLocal_Celta de Vigo',
 'EquipoLocal_Elche',
 'EquipoLocal_Espanol',
 'EquipoLocal_Granada',
 'EquipoLocal_Las Palmas',
 'EquipoLocal_Real Madrid',
 'EquipoLocal_Real Sociedad',
 'EquipoLocal_Sabadell',
 'EquipoLocal_Sevilla',
 'EquipoLocal_Sporting de Gijon',
 'EquipoLocal_Valencia',
 'EquipoLocal_Zaragoza',
 'EquipoVisitante_Atletico de Bilbao',
 'EquipoVisitante_Atletico de Madrid',
 'EquipoVisitante_Barcelona',
 'EquipoVisitante_CD Malaga',
 'Equipo

In [24]:
len(cols)

53

In [25]:
cols2=cols[21:53]+ cols[0:20]+ [cols[20]]

In [26]:
cols2

['EquipoLocal_Atletico de Bilbao',
 'EquipoLocal_Atletico de Madrid',
 'EquipoLocal_Barcelona',
 'EquipoLocal_CD Malaga',
 'EquipoLocal_Celta de Vigo',
 'EquipoLocal_Elche',
 'EquipoLocal_Espanol',
 'EquipoLocal_Granada',
 'EquipoLocal_Las Palmas',
 'EquipoLocal_Real Madrid',
 'EquipoLocal_Real Sociedad',
 'EquipoLocal_Sabadell',
 'EquipoLocal_Sevilla',
 'EquipoLocal_Sporting de Gijon',
 'EquipoLocal_Valencia',
 'EquipoLocal_Zaragoza',
 'EquipoVisitante_Atletico de Bilbao',
 'EquipoVisitante_Atletico de Madrid',
 'EquipoVisitante_Barcelona',
 'EquipoVisitante_CD Malaga',
 'EquipoVisitante_Celta de Vigo',
 'EquipoVisitante_Elche',
 'EquipoVisitante_Espanol',
 'EquipoVisitante_Granada',
 'EquipoVisitante_Las Palmas',
 'EquipoVisitante_Real Madrid',
 'EquipoVisitante_Real Sociedad',
 'EquipoVisitante_Sabadell',
 'EquipoVisitante_Sevilla',
 'EquipoVisitante_Sporting de Gijon',
 'EquipoVisitante_Valencia',
 'EquipoVisitante_Zaragoza',
 'JEquipo1_(N-5)',
 'JEquipo1_(N-4)',
 'JEquipo1_(N-3)',

In [27]:
len(cols2)

53

In [28]:
Temporada70=Temporada70[cols2]

In [29]:
Temporada70

EquipoLocal_Atletico de Bilbao  ...  Resultado
0                                 1  ...          1
1                                 0  ...          1
2                                 0  ...          1
3                                 0  ...          2
4                                 0  ...          1
..                              ...  ...        ...
195                               0  ...          1
196                               0  ...          1
197                               0  ...          0
198                               0  ...          2
199                               0  ...          0

[200 rows x 53 columns]

#Partición del dataset

In [30]:
X = Temporada70.values[:,:-1]
Y = Temporada70.values[:,-1]

In [31]:
from sklearn.model_selection import train_test_split

In [32]:
(trainData, testData, trainLabels, testLabels) = train_test_split(X, Y, test_size=0.2, random_state=84)

#KNN

In [33]:
from sklearn.neighbors import KNeighborsClassifier
for k in range(1,26,2):
    modelKNN = KNeighborsClassifier(n_neighbors=k)
    modelKNN.fit(trainData, trainLabels)
    score = modelKNN.score(testData,testLabels)
    print("k=%d, precisión=%.2f%%" % (k, score * 100))

k=1, precisión=50.00%
k=3, precisión=45.00%
k=5, precisión=42.50%
k=7, precisión=45.00%
k=9, precisión=45.00%
k=11, precisión=47.50%
k=13, precisión=50.00%
k=15, precisión=52.50%
k=17, precisión=52.50%
k=19, precisión=52.50%
k=21, precisión=52.50%
k=23, precisión=52.50%
k=25, precisión=52.50%


In [34]:
modelKNN=KNeighborsClassifier(n_neighbors=23)
modelKNN.fit(trainData, trainLabels)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=23, p=2,
                     weights='uniform')

In [35]:
PrediccionesKNN=modelKNN.predict(testData)                      

In [36]:
Comparacion=pd.DataFrame({'Real':testLabels,'PrediccionesKNN':PrediccionesKNN})
Comparacion.head(40)

Real  PrediccionesKNN
0      2                1
1      2                1
2      2                1
3      1                1
4      1                1
5      0                1
6      1                1
7      1                1
8      2                1
9      0                1
10     1                1
11     1                1
12     2                1
13     1                1
14     1                1
15     1                1
16     0                1
17     0                1
18     1                1
19     0                1
20     0                1
21     1                1
22     2                1
23     1                1
24     0                1
25     1                1
26     1                1
27     2                1
28     1                1
29     1                1
30     2                1
31     1                1
32     1                1
33     1                1
34     0                1
35     0                1
36     1                1
37     2                1
38     1                1
39     0                1

In [37]:
Comparacion.transpose()

0   1   2   3   4   5   6   7   ...  32  33  34  35  36  37  38  39
Real              2   2   2   1   1   0   1   1  ...   1   1   0   0   1   2   1   0
PrediccionesKNN   1   1   1   1   1   1   1   1  ...   1   1   1   1   1   1   1   1

[2 rows x 40 columns]

In [38]:
from sklearn.metrics import accuracy_score
accuracyKNN=accuracy_score(testLabels,PrediccionesKNN)
accuracyKNN

0.525

La precisión es del 0.525, bastante buena.

In [39]:
print("KNN")
from sklearn.metrics import confusion_matrix
print(confusion_matrix(testLabels,PrediccionesKNN))

KNN
[[ 0 10  0]
 [ 0 21  0]
 [ 0  9  0]]


# Árboles de Decisión

Los árboles de decisión también necesitan que les apliquemos el one-hot encoding antes de entrenar, entonces hacemos:

In [40]:
from sklearn.tree import DecisionTreeClassifier
for k in range(2,11,1):
    modelArbol = DecisionTreeClassifier(random_state=84, min_samples_split=k)
    modelArbol.fit(trainData, trainLabels)
    score = modelArbol.score(testData,testLabels)
    print("k=%d, precisión=%.2f%%" % (k, score * 100))

k=2, precisión=45.00%
k=3, precisión=47.50%
k=4, precisión=42.50%
k=5, precisión=42.50%
k=6, precisión=45.00%
k=7, precisión=45.00%
k=8, precisión=45.00%
k=9, precisión=42.50%
k=10, precisión=45.00%


In [41]:
modelArbol = DecisionTreeClassifier(random_state=84, min_samples_split=3)
modelArbol.fit(trainData, trainLabels)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=3,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=84, splitter='best')

In [42]:
PrediccionesDecisionTree=modelArbol.predict(testData)
PrediccionesDecisionTree

array([1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 2, 1, 2, 1, 0,
       2, 1, 0, 1, 2, 0, 1, 0, 0, 1, 1, 1, 2, 1, 1, 0, 1, 1])

In [43]:
ComparacionDecisionTree=pd.DataFrame({'Real':testLabels,'PrediccionesArboles':PrediccionesDecisionTree})
ComparacionDecisionTree.head(40)

Real  PrediccionesArboles
0      2                    1
1      2                    0
2      2                    1
3      1                    0
4      1                    1
5      0                    0
6      1                    1
7      1                    1
8      2                    0
9      0                    1
10     1                    1
11     1                    1
12     2                    0
13     1                    0
14     1                    1
15     1                    1
16     0                    1
17     0                    2
18     1                    1
19     0                    2
20     0                    1
21     1                    0
22     2                    2
23     1                    1
24     0                    0
25     1                    1
26     1                    2
27     2                    0
28     1                    1
29     1                    0
30     2                    0
31     1                    1
32     1                    1
33     1                    1
34     0                    2
35     0                    1
36     1                    1
37     2                    0
38     1                    1
39     0                    1

In [44]:
ComparacionDecisionTree.transpose()

0   1   2   3   4   5   6   ...  33  34  35  36  37  38  39
Real                  2   2   2   1   1   0   1  ...   1   0   0   1   2   1   0
PrediccionesArboles   1   0   1   0   1   0   1  ...   1   2   1   1   0   1   1

[2 rows x 40 columns]

In [45]:
accuracyDecisionTree=accuracy_score(testLabels,PrediccionesDecisionTree)
accuracyDecisionTree

0.475

In [47]:
print("Decision Trees")
from sklearn.metrics import confusion_matrix
print(confusion_matrix(testLabels,PrediccionesDecisionTree))

Decision Trees
[[ 2  5  3]
 [ 4 16  1]
 [ 6  2  1]]


##Estos 3 algoritmos siguientes no los hemos utilizado para nuestro estudio: SVMs, RL y RLog

#SVMs

In [ ]:
from sklearn.svm import SVC
modelSVMLineal = SVC(kernel="linear")
modelSVMLineal.fit(trainData, trainLabels)
modelSVMLineal.predict(testData)

array([1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 2, 1, 1,
       2, 1, 0, 0, 0, 1, 1, 1, 2, 1, 0, 1, 1, 0, 1, 1, 1, 1])

In [ ]:
PrediccionesSVM=modelSVMLineal.predict(testData)

In [ ]:
ComparacionSVM=pd.DataFrame({'real':testLabels,'predicciones':PrediccionesSVM})
ComparacionSVM.head(40)

real  predicciones
0      2             1
1      2             1
2      2             2
3      1             1
4      1             1
5      0             1
6      1             1
7      1             1
8      2             1
9      0             1
10     1             1
11     1             1
12     2             1
13     1             0
14     1             1
15     1             1
16     0             1
17     0             1
18     1             1
19     0             2
20     0             1
21     1             1
22     2             2
23     1             1
24     0             0
25     1             0
26     1             0
27     2             1
28     1             1
29     1             1
30     2             2
31     1             1
32     1             0
33     1             1
34     0             1
35     0             0
36     1             1
37     2             1
38     1             1
39     0             1

In [ ]:
accuracySVM=accuracy_score(testLabels,PrediccionesSVM)
accuracySVM

0.55

#Regresión Lineal

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
regression_model = LinearRegression()
regression_model.fit(trainData,trainLabels)
y_predicted = regression_model.predict(testData)
y_predicted

array([0.39306641, 1.203125  , 1.19775391, 1.18457031, 0.67285156,
       1.59033203, 0.3671875 , 0.81835938, 1.16992188, 1.37841797,
       1.19628906, 0.95947266, 0.84863281, 0.18066406, 1.69287109,
       1.08935547, 1.66894531, 1.65332031, 0.95068359, 1.71337891,
       1.25634766, 0.80859375, 1.70019531, 0.31884766, 1.45263672,
       0.31152344, 1.17285156, 0.90429688, 0.94384766, 0.20996094,
       0.90087891, 0.53417969, 0.34863281, 1.11328125, 1.60546875,
       1.01220703, 0.92871094, 1.06640625, 1.80126953, 0.91601562])

#Regresión Logística

In [ ]:
from sklearn.linear_model import LogisticRegression
modelLR = LogisticRegression(random_state=84)
modelLR.fit(trainData, trainLabels)
PrediccionesLR=modelLR.predict(testData)
PrediccionesLR

array([0, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 0, 1, 1, 1, 1, 1, 2, 1, 1,
       1, 1, 1, 0, 1, 2, 1, 1, 2, 1, 0, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
ComparacionSVM=pd.DataFrame({'real':testLabels,'predicciones':PrediccionesLR})
ComparacionSVM.head(40)

real  predicciones
0      2             0
1      2             1
2      2             1
3      1             1
4      1             1
5      0             1
6      1             1
7      1             1
8      2             2
9      0             1
10     1             1
11     1             1
12     2             2
13     1             0
14     1             1
15     1             1
16     0             1
17     0             1
18     1             1
19     0             2
20     0             1
21     1             1
22     2             1
23     1             1
24     0             1
25     1             0
26     1             1
27     2             2
28     1             1
29     1             1
30     2             2
31     1             1
32     1             0
33     1             1
34     0             1
35     0             1
36     1             1
37     2             1
38     1             1
39     0             1

In [ ]:
accuracyLR=accuracy_score(testLabels,PrediccionesLR)
accuracyLR

0.55

#Redes neuronales

El modelo perceptron está basado en la regresión lineal por tanto tampoco lo utilizamos para nuestro problema.

In [ ]:
from sklearn.linear_model import Perceptron

for k in range(2,11,1):
  modelPerceptron = Perceptron(max_iter=k,eta0=1.0,random_state=84)
  modelPerceptron.fit(trainData,trainLabels)
  scores = cross_val_score(modelPerceptron,trainData,trainLabels,cv=10)
  print("k=%d, Precisión: %0.2f (+/- %0.2f)" % (k, scores.mean(), scores.std() * 2))

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_stochastic_gradient.py:557: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_stochastic_gradient.py:557: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_stochastic_gradient.py:557: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_stochastic_gradient.py:557: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_mo

k=2, Precisión: 0.59 (+/- 0.29)
k=3, Precisión: 0.46 (+/- 0.27)
k=4, Precisión: 0.47 (+/- 0.34)
k=5, Precisión: 0.57 (+/- 0.30)
k=6, Precisión: 0.59 (+/- 0.14)
k=7, Precisión: 0.57 (+/- 0.24)
k=8, Precisión: 0.61 (+/- 0.13)
k=9, Precisión: 0.58 (+/- 0.16)
k=10, Precisión: 0.55 (+/- 0.26)


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_stochastic_gradient.py:557: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_stochastic_gradient.py:557: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_stochastic_gradient.py:557: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_stochastic_gradient.py:557: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_mo

In [ ]:
from sklearn.linear_model import Perceptron
modelPerceptron = Perceptron(max_iter=8,eta0=1.0,random_state=84)
modelPerceptron.fit(trainData,trainLabels)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_stochastic_gradient.py:557: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)


Perceptron(alpha=0.0001, class_weight=None, early_stopping=False, eta0=1.0,
           fit_intercept=True, max_iter=8, n_iter_no_change=5, n_jobs=None,
           penalty=None, random_state=84, shuffle=True, tol=0.001,
           validation_fraction=0.1, verbose=0, warm_start=False)

In [ ]:
PrediccionesModelPerceptron=modelPerceptron.predict(testData)
PrediccionesModelPerceptron

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 2, 1, 0,
       2, 1, 2, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
ComparacionPerceptron=pd.DataFrame({'real':testLabels,'predicciones':PrediccionesModelPerceptron})
ComparacionPerceptron.head(40)

real  predicciones
0      2             1
1      2             1
2      2             1
3      1             1
4      1             1
5      0             1
6      1             1
7      1             1
8      2             1
9      0             1
10     1             1
11     1             1
12     2             0
13     1             0
14     1             1
15     1             1
16     0             1
17     0             1
18     1             1
19     0             2
20     0             1
21     1             0
22     2             2
23     1             1
24     0             2
25     1             0
26     1             0
27     2             1
28     1             1
29     1             1
30     2             0
31     1             1
32     1             0
33     1             1
34     0             1
35     0             1
36     1             1
37     2             1
38     1             1
39     0             1

In [ ]:
accuracyPerceptron=accuracy_score(testLabels,PrediccionesModelPerceptron)
accuracyPerceptron

0.425

In [ ]:
print("MATRIZ DE CONFUSIÓN USANDO PERCEPTRON")
from sklearn.metrics import confusion_matrix
print(confusion_matrix(testLabels,PrediccionesModelPerceptron))

MATRIZ DE CONFUSIÓN USANDO PERCEPTRON
[[ 0  8  2]
 [ 5 16  0]
 [ 2  6  1]]


Para buscar hiperparámetros en la red neuronal multicapa:

In [ ]:
from sklearn.neural_network import MLPClassifier
modelMultiLayerPerceptron = MLPClassifier()

In [ ]:
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint as sp_randint

def randomsearch(model,parameters):
    print("# Tuning hyper-parameters for %s" % score)
    print()

    clf = RandomizedSearchCV(model, parameters,cv=5)
    clf.fit(trainData, trainLabels)

    print("Best parameters set found on development set:")
    print()
    print(clf.best_params_)
    print()

In [ ]:
randomsearch(modelMultiLayerPerceptron,{'hidden_layer_sizes': [(5,2),(3,3,3),(5,3,2),(5,4,3,2),(5,3)],
                              'activation': ['identity','logistic','tanh','relu'], 'momentum': [0.9,0.95,0.99], 'learning_rate_init': [0.001,0.01,0.1]})

# Tuning hyper-parameters for 0.45



/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


Best parameters set found on development set:

{'momentum': 0.99, 'learning_rate_init': 0.001, 'hidden_layer_sizes': (5, 2), 'activation': 'tanh'}



/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


In [55]:
from sklearn.neural_network import MLPClassifier
modelMultiLayerPerceptron = MLPClassifier(hidden_layer_sizes=(5,2),learning_rate_init=0.001,momentum=0.99,activation='tanh')
modelMultiLayerPerceptron.fit(trainData,trainLabels)

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPClassifier(activation='tanh', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(5, 2), learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=200,
              momentum=0.99, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=None, shuffle=True, solver='adam',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)

Sin embargo, este modelo tiene más hiperparámetros y por lo tanto una búsqueda como en los otros casos no es la mejor opción. De esta forma utilizaremos:

In [64]:
from sklearn.neural_network import MLPClassifier
modelMultiLayerPerceptron = MLPClassifier(hidden_layer_sizes=(3),learning_rate_init=0.01,momentum=0.9)
modelMultiLayerPerceptron.fit(trainData,trainLabels)

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=3, learning_rate='constant',
              learning_rate_init=0.01, max_fun=15000, max_iter=200,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=None, shuffle=True, solver='adam',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)

In [65]:
PrediccionesMLP=modelMultiLayerPerceptron.predict(testData)
PrediccionesMLP

array([0, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 2, 1, 1, 2, 1, 0, 1, 1, 2, 1, 1, 1, 1])

In [66]:
ComparacionMLP=pd.DataFrame({'Real':testLabels,'PrediccionesMLP':PrediccionesMLP})
ComparacionMLP.head(40)

Real  PrediccionesMLP
0      2                0
1      2                1
2      2                1
3      1                1
4      1                1
5      0                1
6      1                1
7      1                1
8      2                2
9      0                1
10     1                1
11     1                1
12     2                2
13     1                0
14     1                1
15     1                1
16     0                1
17     0                1
18     1                1
19     0                1
20     0                1
21     1                1
22     2                1
23     1                1
24     0                1
25     1                0
26     1                1
27     2                2
28     1                1
29     1                1
30     2                2
31     1                1
32     1                0
33     1                1
34     0                1
35     0                2
36     1                1
37     2                1
38     1                1
39     0                1

In [67]:
ComparacionMLP.transpose()

0   1   2   3   4   5   6   7   ...  32  33  34  35  36  37  38  39
Real              2   2   2   1   1   0   1   1  ...   1   1   0   0   1   2   1   0
PrediccionesMLP   0   1   1   1   1   1   1   1  ...   0   1   1   2   1   1   1   1

[2 rows x 40 columns]

In [68]:
accuracyMLP=accuracy_score(testLabels,PrediccionesMLP)
accuracyMLP

0.55

In [70]:
print("Red Neuronal (MLP)")
print(confusion_matrix(testLabels,PrediccionesMLP))

Red Neuronal (MLP)
[[ 0  9  1]
 [ 3 18  0]
 [ 1  4  4]]


# Random Forest

In [71]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

for k in range(10,20):
    modelRandomForest=RandomForestClassifier(max_depth=k,min_samples_leaf=2, n_estimators=15,n_jobs=1,bootstrap=False)
    scores = cross_val_score(modelRandomForest,trainData,trainLabels,cv=10)
    print("k=%d, Precisión: %0.2f (+/- %0.2f)" % (k, scores.mean(), scores.std() * 2))

k=10, Precisión: 0.64 (+/- 0.15)
k=11, Precisión: 0.63 (+/- 0.15)
k=12, Precisión: 0.60 (+/- 0.20)
k=13, Precisión: 0.57 (+/- 0.21)
k=14, Precisión: 0.61 (+/- 0.20)
k=15, Precisión: 0.61 (+/- 0.18)
k=16, Precisión: 0.62 (+/- 0.20)
k=17, Precisión: 0.62 (+/- 0.19)
k=18, Precisión: 0.61 (+/- 0.15)
k=19, Precisión: 0.63 (+/- 0.17)


In [72]:
modelRandomForest=RandomForestClassifier(max_depth=10,min_samples_leaf=2, n_estimators=15,n_jobs=1,bootstrap=False)

In [73]:
modelRandomForest.fit(trainData,trainLabels)

RandomForestClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=10, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=2, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=15, n_jobs=1,
                       oob_score=False, random_state=None, verbose=0,
                       warm_start=False)

In [74]:
PrediccionesRandomForest=modelRandomForest.predict(testData)
PrediccionesRandomForest

array([1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [75]:
ComparacionRandomForest=pd.DataFrame({'Real':testLabels,'PrediccionesRF':PrediccionesRandomForest})
ComparacionRandomForest.head(40)

Real  PrediccionesRF
0      2               1
1      2               1
2      2               1
3      1               0
4      1               1
5      0               1
6      1               1
7      1               1
8      2               1
9      0               1
10     1               1
11     1               1
12     2               0
13     1               0
14     1               1
15     1               1
16     0               1
17     0               1
18     1               1
19     0               1
20     0               1
21     1               0
22     2               1
23     1               1
24     0               2
25     1               1
26     1               1
27     2               1
28     1               1
29     1               1
30     2               1
31     1               1
32     1               1
33     1               1
34     0               1
35     0               1
36     1               1
37     2               1
38     1               1
39     0               1

In [76]:
ComparacionRandomForest.transpose()

0   1   2   3   4   5   6   7   ...  32  33  34  35  36  37  38  39
Real             2   2   2   1   1   0   1   1  ...   1   1   0   0   1   2   1   0
PrediccionesRF   1   1   1   0   1   1   1   1  ...   1   1   1   1   1   1   1   1

[2 rows x 40 columns]

In [77]:
accuracy_score(testLabels,PrediccionesRandomForest)

0.45

In [79]:
print("RANDOM FOREST")
print(confusion_matrix(testLabels,PrediccionesRandomForest))

RANDOM FOREST
[[ 0  9  1]
 [ 3 18  0]
 [ 1  8  0]]
